# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
