# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdoc', '0006_auto_20171130_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
