# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdoc', '0008_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
