# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdoc', '0010_content_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tag',
            field=models.CharField(default='Q issue', max_length=50),
            preserve_default=False,
        ),
    ]
