# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdoc', '0011_issue_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='effected',
            field=models.CharField(default='All', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution',
            field=models.CharField(default='Satya re-imported the holding file', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='tag2',
            field=models.CharField(default='T1 Holdings/avg', max_length=50),
            preserve_default=False,
        ),
    ]
