# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdoc', '0017_auto_20171214_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='detail',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolution',
            field=models.CharField(max_length=500),
        ),
    ]
