# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdoc', '0019_issue_tag3'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='critical',
            field=models.CharField(default='Low', max_length=50),
            preserve_default=False,
        ),
    ]
