# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdoc', '0021_auto_20171226_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='user',
            field=models.CharField(default='rakesh', max_length=100),
            preserve_default=False,
        ),
    ]
